vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            uri_prefix: '%app.path.poster_file%'
            upload_destination:  '%kernel.project_dir%/public%app.path.poster_file%'
            namer: vich_uploader.namer_uniqid

